[deps]
BlochSimulators = "2c9a3a5d-4a8d-4ca7-a6c9-04a38836deab"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
ComputationalResources = "ed09eef8-17a6-5b46-8889-db040fac31e3"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
ImagePhantoms = "71a99df6-f52c-4da1-bd2a-69d6f37f3252"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
Memento = "f28f55f0-a522-5efc-85c2-fe41dfb9b2d9"
PythonPlot = "274fc56d-3b97-40fa-a1cd-1b4a50311bf9"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
TickTock = "9ff05d80-102d-5586-aa04-3a8bd1a90d20"

[compat]
BlochSimulators = "0.2.7"